import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./txiki-test-util.mjs";
import { bundleForTxiki } from "./txiki-bundle.mjs";

const outDir = join(ROOT, ".txiki");
mkdirSync(outDir, { recursive: true });

const entries = {
  server: "server/index.txiki.ts",
  deploy: "server/cli/cli-deploy.ts",
  probe: "server/cli/cli-probe.ts",
  profile: "server/cli/cli-profile.ts",
};

/**
 * The four paths a browser fetches to boot the UI, mapped to the file each is
 * embedded from. The three `.br` entries are the precompressed siblings
 * scripts/build-web.mjs writes; `web/index.html` is embedded as-is because it
 * is under a kilobyte and `/` must answer even a client that does not take
 * brotli. See server/core/embedded-assets.ts for the size arithmetic.
 *
 * Each `type` must be the byte-identical string the *filesystem* path serves
 * for that route, not merely an equivalent spelling of it:
 * scripts/test-runtime-http-smoke.mjs compares Node and txiki responses field
 * by field, so `charset=utf-8` where c.html() writes `charset=UTF-8`, or a
 * charset on `/api-docs.json` where context.ts sends bare `application/json`,
 * fails the parity run even though both are valid media types.
 */
const EMBED = [
  { route: "/", file: "web/index.html", encoding: null, type: "text/html; charset=UTF-8" },
  { route: "/app.js", file: "web/dist/app.js.br", encoding: "br", type: "application/javascript; charset=utf-8" },
  { route: "/styles.css", file: "web/dist/styles.css.br", encoding: "br", type: "text/css; charset=utf-8" },
  { route: "/api-docs.json", file: "web/dist/api-docs.json.br", encoding: "br", type: "application/json" },
];

/**
 * Small text files the binary writes beside itself on first run. Not served
 * over HTTP — they are read off disk by `ensure-main-script.ts` and by the
 * device builder, which needs the three `.d.ts` files as the entire stdlib for
 * device code (the device compile is `noLib` with `types: []`).
 *
 * Without these the executable did not merely degrade, it **crashed at
 * startup**: ensureMainScript() read a templates/ that was not there and the
 * process died with ENOENT before binding a port.
 */
const MATERIALISE = [
  "templates/main.example.ts",
  "types/espruino-lib.d.ts",
  "types/meta.d.ts",
  "types/shelly.d.ts",
];

/**
 * Writes the module that replaces server/core/embedded-assets.ts in the server
 * bundle. Generated as JS under `.txiki/` rather than checked in as TS so that
 * `typecheck:server` never sees imports of build outputs that a clean checkout
 * does not have.
 *
 * Hard-fails on a missing input: a silently half-embedded binary is exactly the
 * bug this whole mechanism exists to fix — it would boot, serve `/api/*` and
 * 500 on the UI, which is what shipped in v0.0.2.
 */
function writeEmbeddedModule() {
  const missing = [...EMBED.map((a) => a.file), ...MATERIALISE].filter(
    (f) => !existsSync(join(ROOT, f)),
  );
  if (missing.length) {
    console.error(
      `FAIL: build-txiki.mjs cannot embed ${missing.join(", ")} — run: npm run build:web`,
    );
    process.exit(1);
  }

  const imports = EMBED.map((a, i) => `import a${i} from ${JSON.stringify(join(ROOT, a.file))};`);
  const encode = (a) =>
    a.encoding === null
      ? `bytes: new TextEncoder().encode(a{i}), encoding: null`
      : `bytes: a{i}, encoding: ${JSON.stringify(a.encoding)}`;
  const entriesSrc = EMBED.map(
    (a, i) =>
      `  ${JSON.stringify(a.route)}: { ${encode(a).replaceAll("{i}", String(i))}, type: ${JSON.stringify(a.type)} },`,
  );

  const src = [
    "// GENERATED by scripts/build-txiki.mjs — do not edit, do not commit.",
    "// Replaces server/core/embedded-assets.ts in the txiki server bundle.",
    ...imports,
    "export const EMBEDDED_ASSETS = {",
    ...entriesSrc,
    "};",
    "export function embeddedAsset(path) {",
    "  return Object.prototype.hasOwnProperty.call(EMBEDDED_ASSETS, path)",
    "    ? EMBEDDED_ASSETS[path]",
    "    : undefined;",
    "}",
    "export const EMBEDDED_FILES = {",
    ...MATERIALISE.map(
      (f) => `  ${JSON.stringify(f)}: ${JSON.stringify(readFileSync(join(ROOT, f), "utf8"))},`,
    ),
    "};",
    "export async function materialiseEmbeddedFiles(root, fs, path) {",
    "  for (const [relative, contents] of Object.entries(EMBEDDED_FILES)) {",
    "    const target = path.join(root, relative);",
    "    if (await fs.exists(target)) continue;",
    "    await fs.mkdir(path.dirname(target), { recursive: true });",
    "    await fs.atomicWriteText(target, contents);",
    "  }",
    "}",
    "",
  ].join("\n");

  const generatedPath = join(outDir, "embedded-assets.generated.js");
  writeFileSync(generatedPath, src);
  const embedded = EMBED.reduce((n, a) => n + statSync(join(ROOT, a.file)).size, 0);
  console.log(`txiki embed: ${EMBED.length} browser assets (${embedded} bytes)`);
  return { realPath: join(ROOT, "server", "core", "embedded-assets.ts"), generatedPath };
}

const embeddedAssets = writeEmbeddedModule();

// Sequential, not Promise.all: esbuild parallelises inside one build already,
// and four concurrent 6 MB graphs only fight over the same cores while making
// the failure output interleave.
for (const [name, entry] of Object.entries(entries)) {
  const outFile = join(outDir, `${name}.js`);
  await bundleForTxiki(join(ROOT, entry), outFile, name === "server" ? { embeddedAssets } : {});
  console.log(`txiki bundle: ${outFile} (${statSync(outFile).size} bytes)`);
}
