/**
 * Turn the Playwright capture into something Remotion can cut, and hand it the
 * beat boundaries as frame numbers.
 *
 * Input, both written by `e2e/capture/demo.spec.ts`:
 *   .tmp/capture/demo.webm        variable-frame-rate screencast, 1620×908
 *   .tmp/capture/demo.beats.json  [{ index, key, startMs, endMs }]
 *
 * Output:
 *   video/public/demo.source.mp4  constant 30 fps, near-lossless
 *   video/src/beats.generated.ts  the same spans, in frames
 *
 * ## Why a CFR intermediate
 *
 * `page.screencast` emits a frame only when the page paints, so the webm is
 * variable-frame-rate. `<Video>` from `@remotion/media` seeks by timestamp, and
 * on VFR input that seek lands on the nearest *available* frame — which shows
 * up as a duplicated or skipped frame exactly at a chapter boundary, the one
 * place in the cut where a viewer is looking for a clean edit. So: one pass to
 * constant 30 fps, and let Remotion own the only lossy encode that ships.
 *
 * CRF 16, not the delivery CRF: this file is Remotion's *input*. Encoding it at
 * delivery quality would stack two lossy passes on the same UI text. It is
 * large (~15–25 MB) and never committed — `video/public/` is gitignored.
 *
 * `-pix_fmt yuv420p` is kept even here so the intermediate decodes in the same
 * Chrome the studio preview uses, and `-fps_mode cfr` is the current spelling
 * (`-vsync` is deprecated in ffmpeg 9).
 *
 * ## Why the frame numbers are generated, not typed
 *
 * Every timing tweak in the capture spec moves every later beat. A hand-typed
 * frame table would be wrong one edit after it was written, and wrong in a way
 * that looks like a Remotion bug — chapter 3's title over chapter 2's footage.
 * The manifest is measured during the capture; this script is the only place
 * that converts it, so ms → frames rounding happens once.
 *
 * Usage: node scripts/normalize-capture.mjs
 *        (or `mise run capture:clips`, which shoots the capture first)
 */
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, ".tmp", "capture", "demo.webm");
const MANIFEST = join(ROOT, ".tmp", "capture", "demo.beats.json");
const PUBLIC = join(ROOT, "video", "public");
const OUT = join(PUBLIC, "demo.source.mp4");
const BEATS_TS = join(ROOT, "video", "src", "beats.generated.ts");

/** The composition's frame rate. Must match `FPS` in video/src/Root.tsx. */
const FPS = 30;

function fail(msg) {
  console.error(`FAIL: ${msg}`);
  process.exit(1);
}

if (!existsSync(SRC) || !existsSync(MANIFEST)) {
  fail(
    `${existsSync(SRC) ? MANIFEST : SRC} missing — shoot the capture first:\n` +
      "       playwright test -c e2e/playwright.capture.config.ts demo\n" +
      "       (or `mise run capture:clips`, which does both)",
  );
}

const beats = JSON.parse(readFileSync(MANIFEST, "utf8"));
if (!Array.isArray(beats) || beats.length === 0) fail(`${MANIFEST} holds no beats`);

mkdirSync(PUBLIC, { recursive: true });

const r = spawnSync(
  "ffmpeg",
  [
    // Quiet but not silent: `-stats` keeps one rewriting progress line, which
    // is the difference between "working" and "hung" on a minute-long encode.
    "-hide_banner", "-loglevel", "error", "-stats",
    "-y",
    "-i", SRC,
    "-fps_mode", "cfr",
    "-r", String(FPS),
    "-c:v", "libx264",
    "-pix_fmt", "yuv420p",
    "-crf", "16",
    "-preset", "medium",
    "-movflags", "+faststart",
    "-an",
    OUT,
  ],
  { cwd: ROOT, stdio: ["ignore", "inherit", "inherit"] },
);
if (r.error?.code === "ENOENT") {
  fail("ffmpeg not found — install it (macOS: `brew install ffmpeg`) and re-run");
}
if (r.status !== 0) fail(`ffmpeg failed normalizing the capture (exit ${r.status})`);

const toFrame = (ms) => Math.round((ms / 1000) * FPS);

/**
 * A beat's own span, clamped so consecutive beats never overlap by a frame.
 * The manifest measures wall-clock instants, so beat N's `endMs` and beat N+1's
 * `startMs` are the same moment give or take a millisecond; rounding both to
 * frames can put them on the same frame or one apart in either direction.
 */
const rows = beats.map((b, i) => {
  const start = toFrame(b.startMs);
  const nextStart = i + 1 < beats.length ? toFrame(beats[i + 1].startMs) : toFrame(b.endMs);
  return { key: b.key, start, duration: Math.max(1, nextStart - start) };
});

const total = rows.at(-1).start + rows.at(-1).duration;

writeFileSync(
  BEATS_TS,
  `/**
 * GENERATED by scripts/normalize-capture.mjs — do not edit.
 *
 * Where each beat of \`e2e/capture/demo.spec.ts\` sits in
 * \`public/demo.source.mp4\`, in frames at ${FPS} fps. Regenerated by
 * \`mise run capture:clips\`; a hand edit here is lost on the next re-shoot and,
 * worse, silently puts one chapter's title over another chapter's footage.
 *
 * \`start\` is the frame to trim the footage to (\`trimBefore\`); \`duration\` is
 * how long that beat runs before the next one starts.
 */
export type BeatKey = ${rows.map((b) => JSON.stringify(b.key)).join(" | ")};

export const FOOTAGE_FPS = ${FPS};
export const FOOTAGE_FRAMES = ${total};

export const BEATS: Record<BeatKey, { start: number; duration: number }> = {
${rows.map((b) => `  ${JSON.stringify(b.key)}: { start: ${b.start}, duration: ${b.duration} },`).join("\n")}
};
`,
);

const bytes = statSync(OUT).size;
console.log(`video/public/demo.source.mp4    ${bytes} B, ${total} frames @ ${FPS} fps`);
for (const b of rows) {
  console.log(`  ${b.key.padEnd(12)} start ${String(b.start).padStart(5)}  ${b.duration} frames`);
}
console.log(`video/src/beats.generated.ts    ${rows.length} beats`);
console.log("OK: capture normalized");
