export const el = {
  editor: document.getElementById("editor")!,
  save: document.getElementById("btnSave") as HTMLButtonElement,
  autoBuildCheck: document.getElementById("autoBuildCheck") as HTMLInputElement,
  build: document.getElementById("btnBuild") as HTMLButtonElement,
  buildLabel: document.getElementById("btnBuildLabel")!,
  buildMenuBtn: document.getElementById("btnBuildMenu") as HTMLButtonElement,
  buildMenu: document.getElementById("buildMenu") as HTMLUListElement,
  buildSplit: document.getElementById("buildSplit") as HTMLDivElement,
  deploy: document.getElementById("btnDeploy") as HTMLButtonElement,
  deployMenuBtn: document.getElementById("btnDeployMenu") as HTMLButtonElement,
  deployMenu: document.getElementById("deployMenu") as HTMLUListElement,
  deploySplit: document.getElementById("deploySplit") as HTMLDivElement,
  probe: document.getElementById("btnProbe") as HTMLButtonElement,
  probeProgress: document.getElementById("probeProgress") as HTMLDivElement,
  probeProgressFill: document.getElementById("probeProgressFill") as HTMLDivElement,
  probeSplit: document.getElementById("probeSplit") as HTMLDivElement,
  probeLogToggle: document.getElementById("btnProbeLog") as HTMLButtonElement,
  probeLog: document.getElementById("probeLog") as HTMLDivElement,
  probeLogNote: document.getElementById("probeLogNote")!,
  probeLogFilter: document.getElementById("probeLogFilter") as HTMLInputElement,
  probeLogFailBtn: document.getElementById("probeLogFailBtn") as HTMLButtonElement,
  probeLogList: document.getElementById("probeLogList")!,
  checkPanel: document.getElementById("checkPanel")!,
  checkHead: document.getElementById("checkHead")!,
  checkToggle: document.getElementById("checkToggle")!,
  checkPeek: document.getElementById("checkPeek")!,
  checkNote: document.getElementById("checkNote")!,
  checkRules: document.getElementById("checkRules")!,
  findingsList: document.getElementById("findingsList")!,
  copyFindings: document.getElementById("copyFindings") as HTMLButtonElement,
  status: document.getElementById("statusLine")!,
  buildPanel: document.getElementById("buildPanel")!,
  buildHead: document.getElementById("buildHead")!,
  buildToggle: document.getElementById("buildToggle")!,
  sizeDebug: document.getElementById("sizeDebug")!,
  sizeProd: document.getElementById("sizeProd")!,
  devicePanel: document.getElementById("devicePanel")!,
  deviceHead: document.getElementById("deviceHead")!,
  deviceToggle: document.getElementById("deviceToggle")!,
  devicePeek: document.getElementById("devicePeek")!,
  deviceBody: document.getElementById("deviceBody")!,
  deviceMeta: document.getElementById("deviceMeta")!,
  deviceErr: document.getElementById("deviceErr")!,
  ecoToggle: document.getElementById("ecoToggle") as HTMLInputElement,
  dRunning: document.getElementById("dRunning")!,
  dMem: document.getElementById("dMem")!,
  dCpu: document.getElementById("dCpu")!,
  dRam: document.getElementById("dRam")!,
  dFs: document.getElementById("dFs")!,
  dLatency: document.getElementById("dLatency")!,
  dTemp: document.getElementById("dTemp")!,
  dRssi: document.getElementById("dRssi")!,
  gMem: document.getElementById("gMem")!,
  gCpu: document.getElementById("gCpu")!,
  gRam: document.getElementById("gRam")!,
  gFs: document.getElementById("gFs")!,
};
